const body=document.body,canvas=document.getElementById('canvas'),paper=document.getElementById('paper'),ctx=canvas.getContext('2d'),statusEl=document.getElementById('status'),toast=document.getElementById('toast');let tool='pen',drawing=false,last,history=[],seconds=1500,timer;
function size(){canvas.width=paper.clientWidth*devicePixelRatio;canvas.height=paper.clientHeight*devicePixelRatio;canvas.style.width=paper.clientWidth+'px';canvas.style.height=paper.clientHeight+'px';ctx.scale(devicePixelRatio,devicePixelRatio)}
function msg(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2100)}function pos(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*paper.clientWidth/r.width,y:(e.clientY-r.top)*paper.clientHeight/r.height}}
function brush(){let c=document.getElementById('color').value;ctx.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';ctx.strokeStyle=tool==='highlighter'?c+'66':c;ctx.lineWidth=tool==='highlighter'?22:tool==='chalk'?7:tool==='glitter'?5:3;ctx.lineCap='round';ctx.globalAlpha=tool==='chalk'?.65:1;ctx.setLineDash(tool==='chalk'?[2,3]:[])}function down(e){if(tool==='note'){addNote(e);return}drawing=true;last=pos(e);history.push(canvas.toDataURL());brush()}function move(e){if(!drawing)return;let p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();if(tool==='glitter'){ctx.fillStyle=document.getElementById('color').value;for(let i=0;i<3;i++)ctx.fillRect(p.x+(Math.random()-.5)*15,p.y+(Math.random()-.5)*15,2,2)}last=p;statusEl.textContent='• Unsaved changes'}function up(){drawing=false}function addNote(e){let p=pos(e),n=document.createElement('textarea');n.className='user-note';n.placeholder='Write a note…';n.style.left=Math.min(p.x,paper.clientWidth-165)+'px';n.style.top=Math.min(p.y,paper.clientHeight-125)+'px';document.getElementById('stickies').appendChild(n);n.focus();statusEl.textContent='• Unsaved changes'}canvas.onpointerdown=down;canvas.onpointermove=move;window.onpointerup=up;
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.getElementById('color').oninput=e=>e.target.nextElementSibling.style.background=e.target.value;document.getElementById('undo').onclick=()=>{let src=history.pop();if(!src)return;let i=new Image;i.onload=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(i,0,0,paper.clientWidth,paper.clientHeight)};i.src=src};
document.getElementById('save').onclick=()=>{let notes=[...document.querySelectorAll('.user-note')].map(n=>({text:n.value,left:n.style.left,top:n.style.top}));localStorage.setItem('yalumy-demo',JSON.stringify({drawing:canvas.toDataURL(),notes}));statusEl.textContent='✓ Saved on this device';msg('Your work was saved')};
function restore(){try{let d=JSON.parse(localStorage.getItem('yalumy-demo'));if(!d)return;let i=new Image;i.onload=()=>ctx.drawImage(i,0,0,paper.clientWidth,paper.clientHeight);i.src=d.drawing;(d.notes||[]).forEach(v=>{let n=document.createElement('textarea');n.className='user-note';n.value=v.text;n.style.left=v.left;n.style.top=v.top;document.getElementById('stickies').appendChild(n)});statusEl.textContent='✓ Restored from this device'}catch{}}if(localStorage.getItem('yalumy-theme')==='dark')body.classList.add('dark');document.getElementById('theme').onclick=()=>{body.classList.toggle('dark');localStorage.setItem('yalumy-theme',body.classList.contains('dark')?'dark':'light')};
document.querySelectorAll('.difficulty button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.difficulty button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelectorAll('[data-ai]').forEach(b=>b.onclick=()=>msg('Coming with Yalumy Plus accounts'));
function show(){document.getElementById('time').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')}document.getElementById('start').onclick=e=>{if(timer){clearInterval(timer);timer=null;e.target.textContent='▶ Start';return}e.target.textContent='Ⅱ Pause';timer=setInterval(()=>{if(seconds){seconds--;show()}else{clearInterval(timer);msg('Focus session complete')}},1000)};document.getElementById('reset').onclick=()=>{clearInterval(timer);timer=null;seconds=1500;show();document.getElementById('start').textContent='▶ Start'};document.getElementById('menu').onclick=()=>document.getElementById('sidebar').classList.toggle('open');size();restore();
